### ISSUE TITLE
Autocomplete Issue when deleting text

### ISSUE THREAD

**Issue by ueltje** [DotNetKit/DotNetKit.Wpf.AutoCompleteComboBox#1]
Hi,
your ComboBox is great and works fine. However i discovered a little issue and i would be very greatful if you could solve that:

I use the combobox like this:
`<dotNetKitControls:AutoCompleteComboBox
ItemsSource="{Binding myList}" 
DisplayMemberPath="myStringItemOfmyList"
TextSearch.TextPath="myStringItemOfmyList"
SelectedItem="{Binding anotherValue}"
SelectionChanged="Method_SelectionChanged"
/>`

The first item of the list is auto selected when starting the program. Also this item is on focus (the text is marked) when starting.

When I now press any key to clear the marked text and search for another string, this new entered character is displayed for a very short moment. After that, the ComboBox jumps back to the initially displayed value.

Also when I delete characters of the current displayed string one after another, the following behavour occurs: Once i deleted enough characters, that more than one string would match on my current input, the ComboBox also jumps back to the initial value.

Hope my description helps. If you need more info, please ask me.

Thanks a lot in advance vor your support.

**Comment by vain0** [comment]
Hello. Thanks for reporting.

I reproduced the behavior in question, fixed and deployed.

## Repro steps
(1)
- Select `Alanna Cloninger`
- Select all text
- Input `al`.

(2)
- Select `Alanna Cloninger`
- Delete characters with pressing the backspace key
- When `Alanna`, the text changing to `Alanna Cloninger`
